title: Minesdeep Wiki
description: A collection of information regarding Minesdeep's universe.
language: en-US

theme: jekyll-theme-minimal
show_downloads: false

collections:
  history:
    output: true
  gods:
    output: true

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
