source 'https://rubygems.org'

gem 'jekyll'
gem 'webrick'
gem 'nereare_grimoire', '~> 1.13.13'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-redirect-from'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jemoji'
  gem 'jekyll-spaceship'
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo'
  gem 'tzinfo-data'
end
gem 'wdm', :platforms => [:mingw, :x64_mingw, :mswin]
gem 'http_parser.rb', :platforms => [:jruby]
