source "https://rubygems.org"

gem "just-the-docs"

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
  gem "jekyll-spaceship"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
platforms :mingw, :x64_mingw, :mswin do
  gem "wdm", "~> 0.1"
end
platforms :jruby do
  gem "http_parser.rb", "~> 0.6.0"
end
